name: Docker Image CI VM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: 'read'
  packages: 'read'
  
env:
  DOCKER_IMAGE_NAME: joeting91/pythonblog
  TAG: latest
  AZURE_WEBAPP_NAME: blogapp2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}   
        
    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v0.1.8
      with:
         key: ${{secrets.SSH_PRIVATE_KEY}}
         host: ${{secrets.SSH_HOST}} 
         username: ${{secrets.SSH_USERNAME}}
         script: |
            IMAGE_NAME='${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}' 
            CONTAINER=$(docker ps | grep $IMAGE_NAME | awk '{print $1;}') 
            docker kill pyblog0 
            docker kill pyblog1 
            docker kill pyblog2 
            docker pull $IMAGE_NAME
            docker rm pyblog0
            docker rm pyblog1
            docker rm pyblog2
            docker run -d -p 5000:5000 --name pyblog0 $IMAGE_NAME
            docker run -d -p 5001:5000 --name pyblog1 $IMAGE_NAME
            docker run -d -p 5002:5000 --name pyblog2 $IMAGE_NAME
    # - name: Deploy to Second Azure VM
    #   uses: appleboy/ssh-action@v0.1.8
    #   with:
    #      key: ${{secrets.SSH_PRIVATE_KEY}}
    #      host: ${{secrets.SSH_HOST2}} 
    #      username: ${{secrets.SSH_USERNAME}}
    #      script: |
    #         IMAGE_NAME='${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}' 
    #         CONTAINER=$(docker ps | grep $IMAGE_NAME | awk '{print $1;}') 
    #         docker kill $CONTAINER 
    #         docker pull $IMAGE_NAME
    #         docker run -d -p 5000:5000 $IMAGE_NAME

  
  

          
        
